In [4]:
import datetime
import pandas as pd
import numpy as np



percentage = 10

dates = datetime.datetime(2018,1,1)
datestring = dates.strftime("%Y-%m")
filename  = 'DATA/'+ str(2018)+ '/Data_' + datestring + '.csv'
print(filename)
DF = pd.read_csv(filename)

for year in range(2018,2023):

    for month in range(1,13):

        dates = datetime.datetime(year,month,1)
        datestring = dates.strftime("%Y-%m")
        filename  = 'DATA/'+ str(year)+ '/Data_' + datestring + '.csv'

        new = pd.read_csv(filename)
        num = round(percentage*new.shape[0]/100)
        new_sample = new.sample(n=num)
        del new

        DF = pd.concat([DF, new_sample])
        

dates = datetime.datetime(2023,1,1)
datestring = dates.strftime("%Y-%m")
filename  = 'DATA/'+ str(2023)+ '/Data_' + datestring + '.csv'

new = pd.read_csv(filename)
num = round(percentage*new.shape[0]/100)
new_sample = new.sample(n=num)
del new

DF = pd.concat([DF, new_sample])

dates = datetime.datetime(2023,2,1)
datestring = dates.strftime("%Y-%m")
filename  = 'DATA/'+ str(2023)+ '/Data_' + datestring + '.csv'

new = pd.read_csv(filename)
num = round(percentage*new.shape[0]/100)
new_sample = new.sample(n=num)
del new

DF = pd.concat([DF, new_sample])

dates = datetime.datetime(2023,3,1)
datestring = dates.strftime("%Y-%m")
filename  = 'DATA/'+ str(2023)+ '/Data_' + datestring + '.csv'

new = pd.read_csv(filename)
num = round(percentage*new.shape[0]/100)
new_sample = new.sample(n=num)
del new

DF = pd.concat([DF, new_sample])
        

        
filename2 = 'DATA/MockDATA.csv'
DF.to_csv(filename2)

DATA/2018/Data_2018-01.csv

In [6]:
DF

,Unnamed: 0,secid,date,symbol,symbol_flag,exdate,last_date,cp_flag,strike_price,best_bid,...,sic,index_flag,exchange_d,class,issue_type,industry_group,issuer,div_convention,exercise_style,am_set_flag
6371,6371,108105,2018-02-28,SPXW 180319P3000000,1,2018-03-19,NaN,P,3000000,279.10,...,9999,1,32768,NaN,A,NaN,CBOE S&P 500 INDEX,I,E,NaN
8954,8954,108105,2018-02-28,SPXW 180420C2500000,1,2018-04-20,2018-02-14,C,2500000,237.40,...,9999,1,32768,NaN,A,NaN,CBOE S&P 500 INDEX,I,E,NaN
9269,9269,108105,2018-02-28,SPXW 180420P2710000,1,2018-04-20,2018-02-28,P,2710000,55.60,...,9999,1,32768,NaN,A,NaN,CBOE S&P 500 INDEX,I,E,NaN
7432,7432,108105,2018-02-28,SPXW 180329C1200000,1,2018-03-29,NaN,C,1200000,1510.90,...,9999,1,32768,NaN,A,NaN,CBOE S&P 500 INDEX,I,E,NaN
357,357,108105,2018-02-28,SPX 180316P2155000,1,2018-03-16,2018-02-28,P,2155000,0.95,...,9999,1,32768,NaN,A,NaN,CBOE S&P 500 INDEX,I,E,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
232286,349962,108105,2023-02-17,SPXW 230301P3700000,1,2023-03-01,2023-02-17,P,3700000,1.00,...,9999,1,32768,NaN,A,NaN,CBOE S&P 500 INDEX,I,E,NaN
53207,170883,108105,2023-02-03,SPXW 230519C1200000,1,2023-05-19,NaN,C,1200000,2927.90,...,9999,1,32768,NaN,A,NaN,CBOE S&P 500 INDEX,I,E,NaN
14517,132193,108105,2023-02-01,SPXW 230421C3375000,1,2023-04-21,NaN,C,3375000,767.20,...,9999,1,32768,NaN,A,NaN,CBOE S&P 500 INDEX,I,E,NaN
120163,237839,108105,2023-02-09,SPXW 230214C4165000,1,2023-02-14,2023-02-09,C,4165000,13.20,...,9999,1,32768,NaN,A,NaN,CBOE S&P 500 INDEX,I,E,NaN
29445,147121,108105,2023-02-02,SPXW 230227P4045000,1,2023-02-27,2023-02-01,P,4045000,26.50,...,9999,1,32768,NaN,A,NaN,CBOE S&P 500 INDEX,I,E,NaN